version: '2'
services:
  data:
    # Need to be defined for sentry; choose which ever 
    # local dir you want to keep the data directories
    volumes:
      - ./data/:/data
      - ./db_data/:/var/lib/postgresql/data
    networks:
      - local

  redis:
    networks:
      - local

  postgres:
    networks:
      - local

  sentry:
    volumes:
      - ./sentry.conf.py:/root/.sentry/sentry.conf.py
      - ./config.yml:/root/.sentry/config.yml
    ports:
      - "8080:8080"
    networks:
      - local

  sentry_celery_beat:
    networks:
      - local

  sentry_celery_worker:
    networks:
      - local

networks:
    local:
        external: true
